# Generated by Django 4.2 on 2023-04-25 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_business_category_menuitem_menu_category_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='customer_user_list',
        ),
        migrations.RemoveField(
            model_name='business',
            name='root_user_list',
        ),
        migrations.RemoveField(
            model_name='business',
            name='staff_user_list',
        ),
        migrations.AddField(
            model_name='business',
            name='customer_user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_user_list', to=settings.AUTH_USER_MODEL, verbose_name='Customer User List'),
        ),
        migrations.AddField(
            model_name='business',
            name='root_user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='root_user_list', to=settings.AUTH_USER_MODEL, verbose_name='Root User List'),
        ),
        migrations.AddField(
            model_name='business',
            name='staff_user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_user_list', to=settings.AUTH_USER_MODEL, verbose_name='Staff User List'),
        ),
    ]
